version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'pipenv sync -d'
      - run:
          name: 'Test'
          command: 'pipenv run pytest --cov=. --cov-report=xml tests/'
      - run:
          name: 'Coveralls'
          command: 'pipenv run coveralls'

workflows:
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: main
